image: bitsrc/stable:latest

variables:
  GIT_USER_NAME: “git_user_name”
  GIT_USER_EMAIL: “git_user_email”

build-job:
  stage: build
  script: 
    - |
      cd test-ws
      gitlab.bit.init
      gitlab.bit.branch-lane
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'