image: bitsrc/stable:latest

variables:
  GIT_USER_NAME: “git_user_name”
  GIT_USER_EMAIL: “git_user_email”

check-updates:
  stage: build
  script: 
    - |
      cd my-workspace-dir
      gitlab.bit.init
      gitlab.bit.dependency-update --allow "all" --branch "main"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'