image: bitsrc/stable:latest

variables:
  GIT_USER_NAME: “git_user_name”
  GIT_USER_EMAIL: “git_user_email”

release-components-job:
  stage: build
  script: 
    - |
      cd my-workspace-dir
      gitlab.bit.init
      gitlab.bit.tag-export
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'